// Generated by gencpp from file odrive_interface/ChangeState.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_MESSAGE_CHANGESTATE_H
#define ODRIVE_INTERFACE_MESSAGE_CHANGESTATE_H

#include <ros/service_traits.h>


#include <odrive_interface/ChangeStateRequest.h>
#include <odrive_interface/ChangeStateResponse.h>


namespace odrive_interface
{

struct ChangeState
{

typedef ChangeStateRequest Request;
typedef ChangeStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeState
} // namespace odrive_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::odrive_interface::ChangeState > {
  static const char* value()
  {
    return "7cf842fa729c0d06e59d479de5a05570";
  }

  static const char* value(const ::odrive_interface::ChangeState&) { return value(); }
};

template<>
struct DataType< ::odrive_interface::ChangeState > {
  static const char* value()
  {
    return "odrive_interface/ChangeState";
  }

  static const char* value(const ::odrive_interface::ChangeState&) { return value(); }
};


// service_traits::MD5Sum< ::odrive_interface::ChangeStateRequest> should match
// service_traits::MD5Sum< ::odrive_interface::ChangeState >
template<>
struct MD5Sum< ::odrive_interface::ChangeStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::odrive_interface::ChangeState >::value();
  }
  static const char* value(const ::odrive_interface::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::odrive_interface::ChangeStateRequest> should match
// service_traits::DataType< ::odrive_interface::ChangeState >
template<>
struct DataType< ::odrive_interface::ChangeStateRequest>
{
  static const char* value()
  {
    return DataType< ::odrive_interface::ChangeState >::value();
  }
  static const char* value(const ::odrive_interface::ChangeStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::odrive_interface::ChangeStateResponse> should match
// service_traits::MD5Sum< ::odrive_interface::ChangeState >
template<>
struct MD5Sum< ::odrive_interface::ChangeStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::odrive_interface::ChangeState >::value();
  }
  static const char* value(const ::odrive_interface::ChangeStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::odrive_interface::ChangeStateResponse> should match
// service_traits::DataType< ::odrive_interface::ChangeState >
template<>
struct DataType< ::odrive_interface::ChangeStateResponse>
{
  static const char* value()
  {
    return DataType< ::odrive_interface::ChangeState >::value();
  }
  static const char* value(const ::odrive_interface::ChangeStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODRIVE_INTERFACE_MESSAGE_CHANGESTATE_H
