// Generated by gencpp from file odrive_interface/ChangeControlModeResponse.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_MESSAGE_CHANGECONTROLMODERESPONSE_H
#define ODRIVE_INTERFACE_MESSAGE_CHANGECONTROLMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odrive_interface
{
template <class ContainerAllocator>
struct ChangeControlModeResponse_
{
  typedef ChangeControlModeResponse_<ContainerAllocator> Type;

  ChangeControlModeResponse_()
    : success(false)  {
    }
  ChangeControlModeResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeControlModeResponse_

typedef ::odrive_interface::ChangeControlModeResponse_<std::allocator<void> > ChangeControlModeResponse;

typedef boost::shared_ptr< ::odrive_interface::ChangeControlModeResponse > ChangeControlModeResponsePtr;
typedef boost::shared_ptr< ::odrive_interface::ChangeControlModeResponse const> ChangeControlModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator1> & lhs, const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator1> & lhs, const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odrive_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odrive_interface/ChangeControlModeResponse";
  }

  static const char* value(const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeControlModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odrive_interface::ChangeControlModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODRIVE_INTERFACE_MESSAGE_CHANGECONTROLMODERESPONSE_H
