(cl:defpackage odrive_interface-srv
  (:use )
  (:export
   "CHANGECONTROLMODE"
   "<CHANGECONTROLMODE-REQUEST>"
   "CHANGECONTROLMODE-REQUEST"
   "<CHANGECONTROLMODE-RESPONSE>"
   "CHANGECONTROLMODE-RESPONSE"
   "CHANGESTATE"
   "<CHANGESTATE-REQUEST>"
   "CHANGESTATE-REQUEST"
   "<CHANGESTATE-RESPONSE>"
   "CHANGESTATE-RESPONSE"
  ))

